spring.application.name=reservation-service
server.port=8081

# ======================
# PostgreSQL
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# dialect (important pentru consistenta)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
security.jwt.secret=change-this-secret-key
security.jwt.expiration=3600000

# ======================
# RabbitMQ
# ======================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest